"""test

Revision ID: f78411fb0e05
Revises: 
Create Date: 2017-08-21 09:11:37.359483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f78411fb0e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_field_settings', sa.Column('user_id', postgresql.UUID(), nullable=False), schema='admin')
    op.drop_constraint('form_field_settings_unique_constraint', 'form_field_settings', schema='admin', type_='unique')
    op.create_unique_constraint('form_field_settings_unique_constraint', 'form_field_settings', ['user_id', 'form_name', 'form_field_name'], schema='admin')
    op.create_foreign_key(None, 'form_field_settings', 'users', ['user_id'], ['id'], source_schema='admin', referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('form_field_settings', 'user', schema='admin')
    op.add_column('form_settings', sa.Column('user_id', postgresql.UUID(), nullable=False), schema='admin')
    op.drop_constraint('form_settings_unique_constraint', 'form_settings', schema='admin', type_='unique')
    op.create_unique_constraint('form_settings_unique_constraint', 'form_settings', ['user_id', 'form_name'], schema='admin')
    op.create_foreign_key(None, 'form_settings', 'users', ['user_id'], ['id'], source_schema='admin', referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('form_settings', 'user', schema='admin')
    op.add_column('submenus', sa.Column('user_id', postgresql.UUID(), nullable=False), schema='admin')
    op.drop_constraint('submenus_unique_constraint', 'submenus', schema='admin', type_='unique')
    op.create_unique_constraint('submenus_unique_constraint', 'submenus', ['user_id', 'submenu_name'], schema='admin')
    op.create_foreign_key(None, 'submenus', 'users', ['user_id'], ['id'], source_schema='admin', referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('submenus', 'user', schema='admin')
    op.add_column('table_column_settings', sa.Column('user_id', postgresql.UUID(), nullable=False), schema='admin')
    op.drop_constraint('table_column_settings_unique_constraint', 'table_column_settings', schema='admin', type_='unique')
    op.create_unique_constraint('table_column_settings_unique_constraint', 'table_column_settings', ['user_id', 'table_name', 'column_name'], schema='admin')
    op.create_foreign_key(None, 'table_column_settings', 'users', ['user_id'], ['id'], source_schema='admin', referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('table_column_settings', 'user', schema='admin')
    op.add_column('table_settings', sa.Column('user_id', postgresql.UUID(), nullable=False), schema='admin')
    op.drop_constraint('table_settings_unique_constraint', 'table_settings', schema='admin', type_='unique')
    op.create_unique_constraint('table_settings_unique_constraint', 'table_settings', ['user_id', 'table_name'], schema='admin')
    op.create_foreign_key(None, 'table_settings', 'users', ['user_id'], ['id'], source_schema='admin', referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('table_settings', 'user', schema='admin')
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='auth')
    op.drop_index('users_role_uindex', table_name='users', schema='auth')
    op.create_unique_constraint(None, 'users', ['role'], schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='auth', type_='unique')
    op.create_index('users_role_uindex', 'users', ['role'], unique=True, schema='auth')
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='auth')
    op.add_column('table_settings', sa.Column('user', sa.VARCHAR(), server_default=sa.text('"current_user"()'), autoincrement=False, nullable=False), schema='admin')
    op.drop_constraint(None, 'table_settings', schema='admin', type_='foreignkey')
    op.drop_constraint('table_settings_unique_constraint', 'table_settings', schema='admin', type_='unique')
    op.create_unique_constraint('table_settings_unique_constraint', 'table_settings', ['user', 'table_name'], schema='admin')
    op.drop_column('table_settings', 'user_id', schema='admin')
    op.add_column('table_column_settings', sa.Column('user', sa.VARCHAR(), server_default=sa.text('"current_user"()'), autoincrement=False, nullable=False), schema='admin')
    op.drop_constraint(None, 'table_column_settings', schema='admin', type_='foreignkey')
    op.drop_constraint('table_column_settings_unique_constraint', 'table_column_settings', schema='admin', type_='unique')
    op.create_unique_constraint('table_column_settings_unique_constraint', 'table_column_settings', ['user', 'table_name', 'column_name'], schema='admin')
    op.drop_column('table_column_settings', 'user_id', schema='admin')
    op.add_column('submenus', sa.Column('user', sa.VARCHAR(), server_default=sa.text('"current_user"()'), autoincrement=False, nullable=False), schema='admin')
    op.drop_constraint(None, 'submenus', schema='admin', type_='foreignkey')
    op.drop_constraint('submenus_unique_constraint', 'submenus', schema='admin', type_='unique')
    op.create_unique_constraint('submenus_unique_constraint', 'submenus', ['user', 'submenu_name'], schema='admin')
    op.drop_column('submenus', 'user_id', schema='admin')
    op.add_column('form_settings', sa.Column('user', sa.VARCHAR(), server_default=sa.text('"current_user"()'), autoincrement=False, nullable=False), schema='admin')
    op.drop_constraint(None, 'form_settings', schema='admin', type_='foreignkey')
    op.drop_constraint('form_settings_unique_constraint', 'form_settings', schema='admin', type_='unique')
    op.create_unique_constraint('form_settings_unique_constraint', 'form_settings', ['user', 'form_name'], schema='admin')
    op.drop_column('form_settings', 'user_id', schema='admin')
    op.add_column('form_field_settings', sa.Column('user', sa.VARCHAR(), server_default=sa.text('"current_user"()'), autoincrement=False, nullable=False), schema='admin')
    op.drop_constraint(None, 'form_field_settings', schema='admin', type_='foreignkey')
    op.drop_constraint('form_field_settings_unique_constraint', 'form_field_settings', schema='admin', type_='unique')
    op.create_unique_constraint('form_field_settings_unique_constraint', 'form_field_settings', ['user', 'form_name', 'form_field_name'], schema='admin')
    op.drop_column('form_field_settings', 'user_id', schema='admin')
    # ### end Alembic commands ###
