from .default_datatable_column_settings import create_default_datatable_column_settings_view
from .default_datatable_settings import create_default_datatable_settings_view
from .default_form_field_settings import create_default_form_field_settings_view
from .default_form_settings import create_default_form_settings_view
from .default_home_settings import create_default_home_settings_view
from .menubar import create_menubar_view
from .submenu_items import create_submenu_items_view
